name: Build
run-name: CI/CD for building docker image for HEY and push to docker hub.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  go_test:
    name: Test Go application
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - uses: actions/checkout@v4
      - name: Install go
        run : |
          tar -C /usr/local -xzf go1.22.0.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin
          go version
      - name: Pull code and run tests
        run: |
          git clone https://github.com/rakyll/hey.git
          cd hey
          go test -v
          

#  test_amd64:
#    name: build docker image and test for linux/amd64 architecture
#    runs-on: ubuntu-latest
#    environment:
#      name: prod
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: build docker image for linux/amd64
#        run: docker build --platform linux/amd64 -t hey .
#
#      - name: check container works properly on linux/amd64
#        run: docker run --rm  hey  -n 10 -c 1 https://google.com
#
#  test_arm64:
#    name: build docker image and test for linux/arm64 architecture
#    runs-on: ubuntu-latest
#    environment:
#      name: prod
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: build docker image for linux/arm64
#        run: |
#          sudo apt-get install -y qemu qemu-user-static
#          docker build --platform linux/arm64 -t hey .
#
#      - name: check container works properly on linux/arm64
#        run: docker run --rm  hey  -n 10 -c 1 https://google.com
#
#  build:
#    name: build docker image and push to docker hub
#    runs-on: ubuntu-latest
#    needs:
#      - test_amd64
#      - test_arm64
#    environment:
#      name: prod
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: login to docker registry
#        uses: docker/login-action@v3
#        with:
#          username: ${{vars.DOCKERHUB_USERNAME}}
#          password: ${{secrets.DOCKERHUB_TOKEN}}
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: build docker image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: |
#            ahmadalsajid/hey:latest
#            ahmadalsajid/hey:alpine3.20-go1.22
